### ISSUE TITLE
[BUG] Unexpected Redirection to Twitter

### ISSUE THREAD

**Issue by vedantag17** [inclinedadarsh/open-spectrum#5]
**Describe the bug**
Unexpected Redirection to Twitter when Clicking the "Watch on YouTube" Button

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://open-spectrum.vercel.app/'
2. Click on the 'Watch on YouTube' button
3. See error

**Expected behaviour**
Clicking the "Watch on YouTube" button should open the YouTube video or channel associated with the content on the website.

**Screenshots**
![image](https://github.com/inclinedadarsh/open-spectrum/assets/118207011/f6c92934-6cd5-4819-994d-2d2aa52db459)
As you can see in the screenshot when I hover over the watch on the YouTube box, the Twitter link is displayed

**Comment by inclinedadarsh** [comment]
Thank you for reporting this issue

Do you want to work on this?

**Comment by shreyap2702** [comment]
please assign this to me , i want to work on this

**Comment by inclinedadarsh** [comment]
Go ahead @shreyap2702 , I have assigned this to you.
Make sure to change link on both the "Watch on YouTube buttons"

Also, thanks to @vedantag17 for raising this issue.
